// Generated by LiveScript 1.2.0
var main;
main = function($scope, $http){
  var ref$, w, h, m, ctx1, ctx2, color;
  ref$ = [$(window).width(), $(window).height(), 60], w = ref$[0], h = ref$[1], m = ref$[2];
  $('#chart1').attr({
    width: w - m * 2,
    height: h - m * 3
  });
  ctx1 = $('#chart1')[0].getContext('2d');
  $scope.chart1 = new Chart(ctx1);
  $('#chart2').attr({
    width: w - m * 2,
    height: h - m * 3
  });
  ctx2 = $('#chart2')[0].getContext('2d');
  $scope.chart2 = new Chart(ctx2);
  $scope.color = color = d3.scale.category20();
  $scope.load = function(){
    $http({
      url: 'donate-group.json',
      method: 'GET'
    }).success(function(d){
      var labels, i$, y, j$, m, datasets, i, ref$, ret;
      $scope.data = d;
      labels = [];
      for (i$ = 2007; i$ <= 2014; ++i$) {
        y = i$;
        for (j$ = 1; j$ <= 12; ++j$) {
          m = j$;
          labels = labels.concat([y + "/" + (m > 9 ? '' : '0') + m]);
          if (m === 8 && y === 2014) {
            break;
          }
        }
        if (m === 8 && y === 2014) {
          break;
        }
      }
      labels = ["2006/12"].concat(labels);
      datasets = [{
        data: [],
        label: "捐款金額",
        strokeColor: "rgba(255,0,0,1)",
        pointColor: "rgba(0,0,0,0.5)",
        pointStrokeColor: "rgba(0,0,0,0.9)"
      }];
      for (i$ = 0; i$ < 96; ++i$) {
        i = i$;
        if (i >= labels.length) {
          break;
        }
        (ref$ = datasets[0]).data = ref$.data.concat([d[i] || 0]);
      }
      ret = {
        labels: labels,
        datasets: datasets
      };
      console.log(ret);
      return $scope.chart1.Line(ret, {
        bezierCurveTension: 0.2,
        animation: false,
        datasetFill: false,
        multiTooltipTemplate: "<%= datasetLabel %> - <%= value %>"
      });
    }).error(function(e){});
    return $http({
      url: 'donate-group2.json',
      method: 'GET'
    }).success(function(data){
      var labels, i$, m, j$, d, datasets, i, ref$, ret;
      $scope.data = data;
      labels = [];
      for (i$ = 6; i$ <= 8; ++i$) {
        m = i$;
        for (j$ = 1; j$ <= 31; ++j$) {
          d = j$;
          if (m === 6 && d === 31) {
            break;
          }
          labels = labels.concat([m + "/" + d]);
        }
      }
      labels = ["05/31"].concat(labels);
      datasets = [{
        data: [],
        label: "捐款金額",
        strokeColor: "rgba(255,0,0,1)",
        pointColor: "rgba(0,0,0,0.5)",
        pointStrokeColor: "rgba(0,0,0,0.9)"
      }];
      for (i$ = 0; i$ < 83; ++i$) {
        i = i$;
        (ref$ = datasets[0]).data = ref$.data.concat([data[i] || 0]);
      }
      ret = {
        labels: labels,
        datasets: datasets
      };
      return $scope.chart2.Line(ret, {
        bezierCurveTension: 0.2,
        animation: false,
        datasetFill: false,
        multiTooltipTemplate: "<%= datasetLabel %> - <%= value %>"
      });
    }).error(function(e){});
  };
  return $scope.load();
};